# Generated by Django 4.2.7 on 2023-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='created_at',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='updated_at',
            field=models.DateField(default=None),
        ),
    ]
