# Generated by Django 4.2.7 on 2023-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0002_alter_fruit_created_at_alter_fruit_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='created_at',
            field=models.DateField(default='YY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='updated_at',
            field=models.DateField(default='YY-MM-DD'),
        ),
    ]
