# Generated by Django 4.2.7 on 2023-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='images')),
                ('level_of_education', models.CharField(max_length=100)),
                ('year_of_graduation', models.DateField(default='YY-MM-DD')),
                ('field_of_study', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('transcript', models.FileField(upload_to='files')),
                ('additional_feedback', models.TextField()),
            ],
        ),
    ]
