# Generated by Django 4.2.7 on 2023-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0006_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='clubs')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value_of_fans', models.IntegerField(default=0)),
                ('league_name', models.CharField(max_length=100)),
            ],
        ),
    ]
